// Mocks generated by Mockito 5.4.6 from annotations
// in horda_local_host/test/pagination/list_view_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:horda_local_host/src/store.dart' as _i3;
import 'package:horda_server/horda_server.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeViewSnapshot_0 extends _i1.SmartFake implements _i2.ViewSnapshot {
  _FakeViewSnapshot_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeQueryResult_1 extends _i1.SmartFake implements _i2.QueryResult {
  _FakeQueryResult_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeQueryForSubscriptionResult_2 extends _i1.SmartFake
    implements _i3.QueryForSubscriptionResult {
  _FakeQueryForSubscriptionResult_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ViewStore].
///
/// See the documentation for Mockito's code generation for more information.
class MockViewStore extends _i1.Mock implements _i3.ViewStore {
  @override
  void startProjectingChanges(_i4.Stream<_i2.ChangeEnvelop>? changes) =>
      super.noSuchMethod(
        Invocation.method(#startProjectingChanges, [changes]),
        returnValueForMissingStub: null,
      );

  @override
  void stopProjectingChanges() => super.noSuchMethod(
    Invocation.method(#stopProjectingChanges, []),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<void> initEntityViews(
    String? entityName,
    String? entityId,
    List<_i2.InitViewData>? views,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#initEntityViews, [entityName, entityId, views]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i2.ViewSnapshot> viewSnapshot(
    String? entityName,
    String? entityId,
    String? viewName,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#viewSnapshot, [entityName, entityId, viewName]),
            returnValue: _i4.Future<_i2.ViewSnapshot>.value(
              _FakeViewSnapshot_0(
                this,
                Invocation.method(#viewSnapshot, [
                  entityName,
                  entityId,
                  viewName,
                ]),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i2.ViewSnapshot>.value(
              _FakeViewSnapshot_0(
                this,
                Invocation.method(#viewSnapshot, [
                  entityName,
                  entityId,
                  viewName,
                ]),
              ),
            ),
          )
          as _i4.Future<_i2.ViewSnapshot>);

  @override
  _i4.Future<_i2.ViewSnapshot> attributeSnapshot(
    String? from,
    String? to,
    String? name,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#attributeSnapshot, [from, to, name]),
            returnValue: _i4.Future<_i2.ViewSnapshot>.value(
              _FakeViewSnapshot_0(
                this,
                Invocation.method(#attributeSnapshot, [from, to, name]),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i2.ViewSnapshot>.value(
              _FakeViewSnapshot_0(
                this,
                Invocation.method(#attributeSnapshot, [from, to, name]),
              ),
            ),
          )
          as _i4.Future<_i2.ViewSnapshot>);

  @override
  _i4.Future<_i2.QueryResult> query({
    required String? actorId,
    required String? name,
    required _i2.QueryDef? query,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#query, [], {
              #actorId: actorId,
              #name: name,
              #query: query,
            }),
            returnValue: _i4.Future<_i2.QueryResult>.value(
              _FakeQueryResult_1(
                this,
                Invocation.method(#query, [], {
                  #actorId: actorId,
                  #name: name,
                  #query: query,
                }),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i2.QueryResult>.value(
              _FakeQueryResult_1(
                this,
                Invocation.method(#query, [], {
                  #actorId: actorId,
                  #name: name,
                  #query: query,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.QueryResult>);

  @override
  _i4.Future<_i3.QueryForSubscriptionResult> queryForSubscription({
    required String? actorId,
    required String? name,
    required _i2.QueryDef? query,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#queryForSubscription, [], {
              #actorId: actorId,
              #name: name,
              #query: query,
            }),
            returnValue: _i4.Future<_i3.QueryForSubscriptionResult>.value(
              _FakeQueryForSubscriptionResult_2(
                this,
                Invocation.method(#queryForSubscription, [], {
                  #actorId: actorId,
                  #name: name,
                  #query: query,
                }),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i3.QueryForSubscriptionResult>.value(
                  _FakeQueryForSubscriptionResult_2(
                    this,
                    Invocation.method(#queryForSubscription, [], {
                      #actorId: actorId,
                      #name: name,
                      #query: query,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i3.QueryForSubscriptionResult>);

  @override
  _i4.Future<void> seed(Map<String, dynamic>? seed) =>
      (super.noSuchMethod(
            Invocation.method(#seed, [seed]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i2.ListItem?> getNextListItem(
    String? entityName,
    String? entityId,
    String? viewName,
    double? afterPos,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getNextListItem, [
              entityName,
              entityId,
              viewName,
              afterPos,
            ]),
            returnValue: _i4.Future<_i2.ListItem?>.value(),
            returnValueForMissingStub: _i4.Future<_i2.ListItem?>.value(),
          )
          as _i4.Future<_i2.ListItem?>);

  @override
  _i4.Future<_i2.ListItem?> getPreviousListItem(
    String? entityName,
    String? entityId,
    String? viewName,
    double? beforePos,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getPreviousListItem, [
              entityName,
              entityId,
              viewName,
              beforePos,
            ]),
            returnValue: _i4.Future<_i2.ListItem?>.value(),
            returnValueForMissingStub: _i4.Future<_i2.ListItem?>.value(),
          )
          as _i4.Future<_i2.ListItem?>);
}
